Juan3
ual/activitysim pull request #7
Opened 2020-05-20 19:40 UTC by jdcaicedo251

2020-05-20 20:01 UTC, mxndrwgrdnr requested changes
i left a few comments suggesting changes you should make before we merge. let's also just keep this open until the area_type imputation is ready as well and we can merge at the same time.

2020-05-20 20:01 UTC, mxndrwgrdnr commented on austin_mp/simulation_mp.py
> +from activitysim.abm.models import initialize_skims_from_beam
These two imports shouldn't be necessary

2020-05-20 20:01 UTC, mxndrwgrdnr commented on austin_mp/simulation_mp.py
> +        pipeline.close_pipeline()
The beam skims step needs to be run before data creation step because the data creation uses an injectable (h3_zone_ids) that is created during skim creation.

2020-05-21 21:41 UTC, closed without merging

2020-05-21 21:42 UTC, jdcaicedo251 commented
abort PR